name: Xcode - Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    env:
      BUILD_TYPE: Release
      BUILD_PATH: build
      QT_VERSION: 6.7.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          target: desktop
          arch: clang_64
          install-deps: 'true'
          cache: 'true'
          aqtversion: '==3.1.*'
          archiveName: MusicBox
      - name: Fetch QCloudMusicApi
        run: |
          git clone --recurse-submodules --depth=1 https://github.com/s12mmm3/QCloudMusicApi.git ../QCloudMusicApi \
          && cd ../QCloudMusicApi \
          && cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_PREFIX_PATH=$(pwd)/../Qt/6.7.0/macos/lib/cmake -GXcode -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
          && cd build \
          && xcodebuild -project QCloudMusicApiProject.xcodeproj -target QCloudMusicApi build -configuration ${{ env.BUILD_TYPE }} ONLY_ACTIVE_ARCH=NO \
          && ln -s ${{ env.BUILD_TYPE }}/bin bin
      - name: Build
        run: |
          xcodebuild -project MusicBox.xcodeproj -scheme MusicBox build -configuration ${{ env.BUILD_TYPE }} CONFIGURATION_BUILD_DIR=$(pwd)/build CODE_SIGN_IDENTITY="-" DEVELOPMENT_TEAM="" ONLY_ACTIVE_ARCH=NO
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.archiveName }}
          path: ${{ github.workspace }}/build
