name: Xcode - Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    env:
      BUILD_TYPE: Release
      BUILD_PATH: build
      QT_VERSION: 6.7.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          target: desktop
          arch: clang_64
          install-deps: 'true'
          cache: 'true'
          aqtversion: '==3.1.*'
      - name: Fetch QCloudMusicApi
        run: |
          git clone --recurse-submodules --depth=1 https://github.com/s12mmm3/QCloudMusicApi.git ../QCloudMusicApi \
          && cd ../QCloudMusicApi \
          && cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_PREFIX_PATH=$(pwd)/../Qt/${{ env.QT_VERSION }}/macos/lib/cmake \
          && cmake --build build -j \
          && cd build && ln -s ${{ env.BUILD_TYPE }}/bin bin
      - name: Build
        run: |
          xcodebuild -project MusicBox.xcodeproj -scheme MusicBox build -configuration Release CONFIGURATION_BUILD_DIR=(pwd)/build
